DROP DATABASE IF EXISTS `DATA_WAREHOUSE`;
CREATE DATABASE `DATA_WAREHOUSE`;
USE `DATA_WAREHOUSE`;

DROP TABLE IF EXISTS FATO;
CREATE TABLE FATO(
# DIMENSÕES 
	ID_CLIENTE INT NOT NULL,
    ID_INVESTIMENTO INT NOT NULL,
    ID_TEMPO INT NOT NULL,
    
# MEDIÇÕES     
    NOVOS_INVESTIMENTOS_DIA FLOAT NOT NULL,
    NOVOS_INVESTIMENTOS_MES FLOAT NOT NULL,
    NOVOS_INVESTIMENTOS_SEMESTRE FLOAT NOT NULL,
    NOVOS_INVESTIMENTOS_ANO FLOAT NOT NULL,
    INVESTIMENTOS_TOTAL FLOAT NOT NULL,
    
    SALDO_INVESTIMENTOS_DIA FLOAT NOT NULL,
    SALDO_INVESTIMENTOS_MES FLOAT NOT NULL,
    SALDO_INVESTIMENTOS_SEMESTRE FLOAT NOT NULL,
    SALDO_INVESTIMENTOS_ANO FLOAT NOT NULL,
    SALDO_INVESTIMENTOS_TOTAL FLOAT NOT NULL,
    
    # RETIRADA = SAQUES (FIXA) || VENDA (VARIADA)
    RETIRADAS_DIA FLOAT NOT NULL,
    RETIRADAS_MES FLOAT NOT NULL,
    RETIRADAS_SEMESTRE FLOAT NOT NULL,
    RETIRADAS_ANO FLOAT NOT NULL,
    RETIRADAS_TOTAL FLOAT NOT NULL,
    
    LUCRO_DIA FLOAT NOT NULL,
    LUCRO_MES FLOAT NOT NULL,
    LUCRO_SEMESTRE FLOAT NOT NULL,
    LUCRO_ANO FLOAT NOT NULL,
    LUCRO_TOTAL FLOAT NOT NULL
);

DROP TABLE IF EXISTS CLIENTES;
CREATE TABLE CLIENTES(
	ID INT PRIMARY KEY,
    
	NOME VARCHAR(30) NOT NULL,
	PERFIL ENUM('CONSERVADOR', 'MODERADO', 'ARROJADO', 'AGRESSIVO')
);

DROP TABLE IF EXISTS TEMPO;
CREATE TABLE TEMPO(
	ID INT PRIMARY KEY,
    
    DIA TINYINT NOT NULL,
    MES TINYINT NOT NULL,
    SEMESTRE TINYINT NOT NULL,
    ANO SMALLINT NOT NULL
    
    # CONSTRAINT DATA_UNICA UNIQUE (DIA, MES, ANO, SEMESTRE)
);

DROP TABLE IF EXISTS INVESTIMENTOS;
CREATE TABLE INVESTIMENTOS(
	ID INT PRIMARY KEY,
    
    TIPO ENUM('ACAO', 'FUNDOS', 'CDB', 'FIXA', 'DIVIDENDOS') NOT NULL
);

INSERT INTO INVESTIMENTOS(ID, TIPO) VALUES (1, 1);
INSERT INTO INVESTIMENTOS(ID, TIPO) VALUES (2, 2);
INSERT INTO INVESTIMENTOS(ID, TIPO) VALUES (3, 3);
INSERT INTO INVESTIMENTOS(ID, TIPO) VALUES (4, 4);
INSERT INTO INVESTIMENTOS(ID, TIPO) VALUES (5, 5);

ALTER TABLE FATO
ADD CONSTRAINT FK_CLIENTE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE FATO
ADD CONSTRAINT FK_OP
FOREIGN KEY (ID_INVESTIMENTO) REFERENCES INVESTIMENTOS(ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE FATO
ADD CONSTRAINT FK_TEMPO
FOREIGN KEY (ID_TEMPO) REFERENCES TEMPO(ID) ON UPDATE CASCADE ON DELETE CASCADE;